// authSlice.ts (No changes to this file, but noting where actions come from)
import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  token: null,
  isAuthenticated: false,
  username: null
};

const authSlice = createSlice({
  name: 'auth',
  initialState,
  reducers: {
    loginSuccess(state, action) {
      state.token = action.payload; // payload is string | null here
      state.isAuthenticated = true;
    },
    logout(state) {
      state.token = null;
      state.isAuthenticated = false;
    },
    setToken(state, action) {
      state.token = action.payload; // payload is string | null here
      state.isAuthenticated = !!action.payload;
    },
    setUsername(state, action) {
      state.username = action.payload; // payload is string | null here
    }
  },
});

export const { loginSuccess, logout, setToken, setUsername } = authSlice.actions;
export default authSlice.reducer;

// Add this type definition to authSlice.ts or a separate types.ts file
// This creates a union type of all actions generated by authSlice
export type AuthActions =
  | ReturnType<typeof loginSuccess>
  | ReturnType<typeof logout>
  | ReturnType<typeof setToken>
  | ReturnType<typeof setUsername>;