// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import Navbar from "./components/Navbar";

export const metadata: Metadata = {
  title: "Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en" data-theme="cupcake">
      <body>
        <header>
        <link rel="icon" href="/favicon.png" />
          <Navbar />
        </header>
        
        <main>{children}</main>

        <footer>
          <p>© 2024 Your Company</p>
        </footer>
      </body>
    </html>
  );
}
